- src/Routes.js
- src/components/molecules/menu/index.js
- src/components/pages/outlet/index.js
- src/components/pages/outlet/style.scss
- src/components/pages/page/index.js
- src/styles/_normalize.scss
> JIRA-00: outlets page ui added

- package-lock.json
- package.json
- src/components/pages/signIn/index.js
- src/components/pages/signUp/index.js
- src/utils/api/auth-api-utils.js
- src/utils/local-storage/local-store-utils.js
- src/utils/url-configs.js
- sign in api call
- sign up api call
> JIRA-00: Signin signup calls

- src/components/organism/table/index.js
- src/components/pages/appShell/index.js
- src/components/pages/appShell/style.scss
- src/components/pages/categories/index.js
- src/components/pages/categories/style.scss
- src/components/pages/outlet/index.js
- src/components/pages/outlet/style.scss
- src/styles/_global.scss
- src/styles/_mixins.scss
- src/styles/_utilities.scss
- mobile responsive layout
- minor UI fixes on category page
> JIRA-00: responsive layout

- src/Routes.js
- src/components/molecules/menu/index.js
- src/components/organism/form/index.js
- src/components/pages/appShell/style.scss
- src/components/pages/categories/categoryAdd/index.js
- src/components/pages/categories/style.scss
- src/components/pages/signUp/index.js
- src/components/pages/suppliers/index.js
- src/components/pages/suppliers/supplierAdd/index.js
- src/styles/_global.scss
- src/styles/_mixins.scss
- src/styles/_utilities.scss
- suppliers page ui added
- category add form
- sass improvements (added @extends)
> JIRA-00: suppliers page ui added

- src/Routes.js
- src/components/molecules/menu/index.js
- src/components/pages/taxes/index.js
- src/components/pages/taxes/taxAdd/index.js
- Taxes page UI added
- Add Tax page added
> JIRA-00: taxes page ui

- src/components/pages/taxes/taxAdd/index.js
- src/utils/api/auth-api-utils.js
- src/utils/api/generic-api-utils.js
- src/utils/api/tax-api-utils.js
- src/utils/constants/constants.js
- src/utils/constants/url-configs.js
- API calls for tax
- generic API call utils
> JIRA-00: Tax add api implementation

- src/Routes.js
- src/components/molecules/menu/index.js
- src/components/pages/categories/categoryAdd/index.js
- src/components/pages/categories/index.js
- src/components/pages/dashboard/index.js
- src/components/pages/outlet/index.js
- src/components/pages/page/index.js
- src/components/pages/products/index.js
- src/components/pages/products/productAdd/index.js
- src/components/pages/products/productAdd/style.scss
- src/components/pages/products/productDiscount/index.js
- src/components/pages/products/productLookup/index.js
- src/components/pages/products/productUpload/index.js
- src/components/pages/signIn/index.js
- src/components/pages/signUp/index.js
- src/components/pages/suppliers/supplierAdd/index.js
- src/components/pages/taxes/index.js
- src/components/pages/taxes/taxAdd/index.js
- src/styles/_global.scss
- src/styles/_typography.scss
- src/styles/_variables.scss
- add new product
- add discount
- product lookup
- bulk upload
> JIRA-00: product pages UI added

- src/Routes.js
- src/components/molecules/menu/index.js
- src/components/pages/customers/customerAdd/index.js
- src/components/pages/customers/index.js
- src/styles/_global.scss
- customers page added
- add customer page added
> JIRA-00: customers pages added

- src/Routes.js
- src/components/molecules/menu/index.js
- src/components/pages/couriers/courierAdd/index.js
- src/components/pages/couriers/index.js
- courier page added
- add new courier page
> JIRA-00: courier pages ui added

- src/Routes.js
- src/components/organism/table/suppliersTable.js
- src/components/pages/suppliers/deleteSupplier.js
- src/components/pages/suppliers/editSupplier.js
- src/components/pages/suppliers/index.js
- src/components/pages/suppliers/supplierAdd/index.js
- src/utils/api/categories-api-utils.js
- src/utils/api/suppliers-api-utils.js
- src/utils/constants/url-configs.js
commit for code changes needed for supplier's module  task functionalities.
> commit for suppliers task functionality

- src/Routes.js
- src/components/organism/table/couriersTable.js
- src/components/pages/couriers/courierAdd/index.js
- src/components/pages/couriers/deleteCourier.js
- src/components/pages/couriers/editCourier.js
- src/components/pages/couriers/index.js
- src/utils/api/categories-api-utils.js
- src/utils/api/couriers-api-utils.js
- src/utils/constants/url-configs.js
commit for couriers module task functionality
> commit for couriers module task functionality

- src/components/pages/appShell/index.js
- src/components/pages/appShell/style.scss
- src/components/pages/outlet/style.scss
- src/styles/_global.scss
- src/styles/_mixins.scss
- src/styles/_variables.scss
- remove stylesheet inconsistencies
- variable list updated
- header structure and style update
- mobile view fixes
> JIRA-00: style-sheet fixes

- src/Routes.js
- src/components/molecules/menu/index.js
- src/components/pages/categories/index.js
- src/components/pages/reports/categoryWise/index.js
- src/components/pages/reports/inventoryDump/index.js
- src/components/pages/reports/omniSalesSummary/index.js
- src/components/pages/reports/productHistory/index.js
- src/components/pages/reports/salesSummary/index.js
- src/components/pages/reports/style.scss
> JIRA-00: report pages ui added

- package-lock.json
- src/Routes.js
- src/components/pages/customers/customerHistory/index.js
- src/components/pages/customers/customerPay/index.js
- src/components/pages/customers/customerProfile/index.js
- src/components/pages/customers/customerProfile/style.scss
- src/styles/_base.scss
- yarn.lock
- credit history
- profile view
- pay balance
> JIRA-00: customer profile pages ui

- src/Routes.js
- src/components/pages/setup/index.js
- src/components/pages/setup/outlets/index.js
- src/components/pages/setup/outlets/outletAdd/index.js
- src/components/pages/setup/receipt/index.js
- src/components/pages/setup/receipt/receiptAdd/index.js
- src/components/pages/setup/users/index.js
- src/components/pages/setup/users/userAdd/index.js
- outlet
- outlet add new
- receipt
- receipt add new
- user
- user add new
> JIRA-00: setup pages added

- src/Routes.js
> JIRA-00: Route fixes

- src/Routes.js
- src/components/pages/stock/index.js
- src/components/pages/stock/order/index.js
> JIRA-00: stock pages

- src/components/pages/reports/salesSummary/index.js
small code tweak for products 's sale summary screen,
> small code tweaks for sales summary screen

- src/Routes.js
- src/components/pages/setup/outlets/outletEdit/index.js
- src/styles/_global.scss
> JIRA-00: outlets edit page

- src/components/pages/dashboard/index.js
- src/components/pages/dashboard/style.scss
> JIRA-00: dashboard skeleton

- package-lock.json
- src/components/pages/register/sell/index.js
- yarn.lock
- register sell page layout changed
> JIRA-00: sell page layout changed

- src/Routes.js
- src/components/molecules/menu/index.js
- src/components/pages/appShell/index.js
- src/components/pages/outlet/index.js
- src/components/pages/signIn/index.js
- src/components/pages/signUp/index.js
- src/utils/api/auth-api-utils.js
- src/utils/api/generic-api-utils.js
- src/utils/api/products-api-utils.js
- src/utils/local-storage/local-store-utils.js
- if a user is not authenticated then he is logged back into the sign-in page
- only user data is wiped if a user is in unauthenticated state
> JIRA-00: Api call auth state

- src/Routes.js
- src/components/organism/table/stock/stockTable.js
- src/components/pages/categories/deleteCategory.js
- src/components/pages/categories/editCategory.js
- src/components/pages/customers/customerForm/index.js
- src/components/pages/register/sell/index.js
- src/components/pages/stock/order/adjustmentStock.js
- src/components/pages/stock/order/index.js
- src/components/pages/stock/order/returnStock.js
- src/components/pages/stock/order/transferInventory.js
- src/components/pages/taxes/deleteTax.js
- src/components/pages/taxes/editTax.js
- src/utils/api/stock-api-utils.js
- src/utils/constants/url-configs.js
commit for minor codebase changes for application's functionalities.
> Mj/minor applications's codebase changes

- src/components/pages/dashboard/index.js
- src/components/pages/dashboard/style.scss
- src/components/pages/outlet/style.scss
- src/components/pages/register/sell/style.scss
- src/styles/_global.scss
- outlet page mobile view fixes
- register page fixes
- dashboard fixes
> JIRA-00: UI fixes

- src/Routes.js
- src/components/molecules/menu/index.js
- src/components/organism/table/reports/categorySalesSummaryTable.js
- src/components/pages/products/productUpload/index.js
- src/components/pages/register/salesHistory/index.js
- src/components/pages/register/sell/index.js
- src/components/pages/stock/Transfer/index.js
- src/components/pages/stock/order/adjustmentStock.js
- src/components/pages/stock/order/index.js
- src/components/pages/stock/order/returnStock.js
- src/components/pages/stock/order/transferInventory.js
- src/utils/api/products-api-utils.js
- src/utils/api/sales-api-utils.js
- src/utils/helpers/scripts.js
- src/utils/local-storage/local-store-utils.js
commit for codebase changes for application's tasks.
> commit for codebase changes for application's tasks

- cloudbuild.yaml
- added YAML file for deployment on GCP
> JIRA-00: Yaml File

- src/components/pages/dashboard/index.js
- src/components/pages/register/sell/index.js
- src/components/pages/setup/users/editUser.js
- src/components/pages/setup/users/userAdd/index.js
- src/components/pages/stock/order/transferInventory.js
- src/utils/api/couriers-api-utils.js
- src/utils/api/setup-api-utils.js
- src/utils/constants/url-configs.js
commit for api routes integration
> commit for api routes integration

- package-lock.json
- src/Routes.js
- src/components/pages/ecommerce/index.js
- src/components/pages/ecommerce/inventorySync/index.js
- src/components/pages/ecommerce/orders/allOrders/index.js
- src/components/pages/ecommerce/orders/completedOrders/index.js
- src/components/pages/ecommerce/orders/index.js
- src/components/pages/ecommerce/orders/saleOrders/index.js
- src/components/pages/ecommerce/style.scss
> JIRA-00: e-commerce pages UI

- src/components/pages/products/productAdd/index.js
- src/components/pages/reports/salesSummary/index.js
- src/components/pages/setup/users/userAdd/index.js
> JIRA-00: commit for qa bugs fixations

- src/components/organism/table/productsNestedTable/productsDiscounts/index.js
- src/components/organism/table/reports/categorySalesSummaryTable.js
- src/components/organism/table/reports/productsMovementReportTable.js
- src/components/pages/products/editProduct.js
- src/components/pages/products/index.js
- src/components/pages/products/productAdd/index.js
- src/components/pages/products/productDiscount/index.js
- src/components/pages/stock/order/index.js
- src/components/pages/stock/order/returnStock.js
commit for minor codebase refactoring and tweaks
> JIRA-00: commit for minor codebase refactoring and tweaks

- src/components/organism/table/productsNestedTable/productsAdd/productsVariantsNestedTable.js
- src/components/pages/products/productAdd/calculateProductsVariantsCombination.js
- src/components/pages/products/productAdd/index.js
- src/components/pages/stock/order/index.js
- src/components/pages/stock/order/returnStock.js
commit for codebase minor changes for products module
> JIRA-00: commit for codebase minor changes for products module

- src/components/organism/table/productsNestedTable/productsAdd/productsVariantsNestedTable.js
- src/components/organism/table/productsNestedTable/productsDiscounts/index.js
- src/components/organism/table/productsNestedTable/productsLookUp/index.js
- src/components/pages/customers/customerForm/index.js
commit for following sub-tasks:
1) codebase improvements and workflows enhancemets changes in products module(i.e product Add functionality).
2) removed some unwanted code and warning issues.
> SD-175: workflows improvements in add product module

- src/components/organism/table/productsNestedTable/productsAdd/index.js
- src/components/organism/table/productsNestedTable/productsAdd/productsVariantsNestedTable.js
- src/components/pages/appShell/index.js
- src/components/pages/appShell/style.scss
- src/components/pages/categories/index.js
- src/components/pages/products/editProduct.js
- src/components/pages/products/productAdd/calculateProductsVariantsCombination.js
- src/components/pages/products/productAdd/index.js
- src/components/pages/signIn/index.js
- src/components/pages/signUp/index.js
- src/components/pages/suppliers/index.js
- src/components/pages/suppliers/supplierAdd/index.js
- src/components/pages/taxes/index.js
- src/styles/_global.scss
- src/styles/_variables.scss
commit for fixations of mb qa issues related to products, customer and taxes module
> SD-185: commit for fixations of mb qa issues

- src/components/organism/table/sell/sellHistoryProductsTable.js
> SD-198: commit for fix of sd-198

- src/Routes.js
- src/components/molecules/menu/index.js
- src/components/molecules/menu/style.scss
- src/components/pages/dashboard/index.js
- src/components/pages/products/productAdd/index.js
- src/components/pages/register/salesHistory/index.js
- src/components/pages/reports/categoryWise/index.js
- src/components/pages/reports/inventoryDump/index.js
- src/components/pages/reports/omniSalesSummary/index.js
- src/components/pages/reports/productHistory/index.js
- src/components/pages/reports/salesSummary/index.js
- src/components/pages/setup/index.js
- src/components/pages/setup/outlets/outletAdd/index.js
- src/components/pages/setup/outlets/outletEdit/index.js
- src/components/pages/setup/receipt/receiptDelete.js
- src/components/pages/setup/receipt/receiptEdit.js
- src/components/pages/setup/users/editUser.js
- src/components/pages/setup/users/userAdd/index.js
- src/components/pages/stock/index.js
fix: commit for fixation of ticket sd-199
> SD-199: commit for fixation of ticket sd-199

- src/components/molecules/menu/index.js
- src/components/organism/table/reports/salesSummaryTable.js
- src/components/organism/table/sell/sellHistoryProductsTable.js
- src/components/pages/register/sell/index.js
- src/components/pages/register/sell/sellInvoice.js
- src/components/pages/signIn/index.js
commit for fixation of issue against ticket sd-163
> SD-163: commit for fixation of issue against ticket sd-163

- src/components/pages/register/sell/index.js
- src/components/pages/register/sell/style.scss
fix: commit for fix related to ticket [sd-166]
> SD-166: commit for fix related to ticket [sd-166]

- src/components/organism/table/sell/sellHistory.scss
- src/components/organism/table/sell/sellHistoryProductsTable.js
- src/components/pages/outlet/index.js
- src/components/pages/register/salesHistory/index.js
- src/components/pages/register/sell/index.js
- src/utils/api/oulets-api-utils.js
- src/utils/constants/url-configs.js
fix: commit for fix of ticket sd-220
> SD-220: commit for fix of ticket sd-220

- src/components/pages/customers/index.js
- src/components/pages/ecommerce/inventorySync/index.js
- src/components/pages/ecommerce/orders/index.js
- src/components/pages/register/salesHistory/index.js
- src/components/pages/register/sell/index.js
- src/components/pages/register/sell/style.scss
- src/utils/api/sales-api-utils.js
- src/utils/constants/url-configs.js
commit for fix to ticket sd-225
> SD-225: commit for fix to ticket sd-225

- src/components/pages/ecommerce/inventorySync/index.js
- src/components/pages/ecommerce/orders/index.js
- src/components/pages/register/salesHistory/index.js
- src/components/pages/register/sell/index.js
- src/components/pages/register/sell/sellInvoice.js
- src/components/pages/register/sell/style.scss
commit for fix to ticket [sd-165]
> SD-165: commit for fix to ticket [sd-165]

- src/Routes.js
- src/components/molecules/menu/index.js
- src/components/organism/table/stock/stockNestedProductsTable.js
- src/components/organism/table/stock/stockReceiveTable.js
- src/components/organism/table/stock/stockTable.js
- src/components/organism/table/stock/viewStockReturnedTable.js
- src/components/pages/products/editProduct.js
- src/components/pages/register/salesHistory/index.js
- src/components/pages/setup/receipt/receiptAdd/index.js
- src/components/pages/stock/ReturnedStock/index.js
- src/components/pages/stock/ReturnedStock/viewStockReturn.js
- src/components/pages/stock/index.js
- src/components/pages/stock/stockReceive/index.js
- src/styles/_base.scss
- src/utils/api/stock-api-utils.js
- src/utils/constants/url-configs.js
> SD-238: commit for fix to [sd-238]

- src/components/molecules/menu/index.js
- src/components/organism/table/stock/stockTable.js
- src/components/organism/table/stock/style.scss
- src/components/organism/table/stock/viewStockReturnedTable.js
- src/components/pages/products/productUpload/index.js
- src/components/pages/stock/ReturnedStock/viewStockReturn.js
- src/components/pages/stock/index.js
> SD-236: commit for fix to [sd-236]

- src/components/organism/table/productsNestedTable/productsTable.js
- src/components/organism/table/productsNestedTable/productsViewNestedTable.js
- src/components/pages/products/index.js
- src/components/pages/register/sell/index.js
- src/components/pages/register/sell/sellInvoice.js
commit for fix to ticket [sd-248]
> SD-248: commit for fix to ticket [sd-248]

- src/components/organism/table/stock/stockNestedProductsTable.js
- src/components/organism/table/stock/style.scss
- src/components/pages/categories/index.js
- src/components/pages/couriers/index.js
- src/components/pages/register/sell/sellInvoice.js
- src/components/pages/stock/order/adjustmentStock.js
- src/components/pages/stock/order/index.js
- src/components/pages/stock/order/transferInventory.js
- src/components/pages/taxes/taxAdd/index.js
commit for fix to ticket [sd-251]
> SD-251: commit for fix to ticket [sd-251]

- src/components/pages/register/salesHistory/index.js
- src/components/pages/register/sell/sellInvoice.js
> SD-235: commit for fix to [sd-235]

- src/components/pages/reports/inventoryDump/index.js
commit for loader display on inventory dump page
> JIRA-00: commit for loader display on inventory dump page

- src/components/organism/table/sell/sellHistoryProductsTable.js
- src/components/pages/products/editProduct.js
- src/components/pages/register/sell/index.js
> SD-258: commit for fix to [sd-258]

- src/components/organism/table/stock/stockNestedProductsTable.js
- src/components/pages/register/salesHistory/index.js
commit for null prices fix in stock control
> JIRA-00: commit for null prices fix in stock control

- src/components/organism/table/reports/salesSummaryTable.js
commit for fixing missing fields data in omni sales summary of reports module
> JIRA-00: fixing missing fields data in reports

- src/components/organism/table/ecommerce/omniSalesOrdersTable.js
> SD-284: commit for fix to [sd-284]

- src/components/organism/table/reports/salesSummaryTable.js
- src/components/organism/table/stock/stockNestedProductsTable.js
commit for adding invoice note column in omni sales summary of reports module.
> JIRA-00: add invoice note column in omni sales

- src/components/pages/reports/inventoryDump/index.js
commit for fixing total units value shown in inventory dump report
> JIRA-00: fixing total value in inventory dump

- src/components/pages/register/sell/index.js
- src/components/pages/register/sell/sellInvoice.js
fixations for register sale page issues
> JIRA-00: fixations for register sale page issues

- src/components/organism/table/productsNestedTable/productsTable.js
- src/components/organism/table/reports/salesSummaryTable.js
- src/components/organism/table/sell/sellHistoryProductsTable.js
- src/components/organism/table/stock/stockReceiveTable.js
- src/components/pages/products/productAdd/index.js
- src/components/pages/register/salesHistory/index.js
- src/components/pages/register/sell/index.js
- src/components/pages/register/sell/sellInvoice.js
- src/components/pages/reports/salesSummary/printOverviewSales.js
- src/components/pages/stock/stockReceive/index.js
> SD-307: shopdesk qa issues fixations

- src/components/organism/table/reports/salesSummaryTable.js
- src/components/organism/table/stock/stockNestedProductsTable.js
- src/components/pages/reports/inventoryDump/index.js
- src/components/pages/reports/omniSalesSummary/index.js
- src/components/pages/reports/salesSummary/index.js
- src/components/pages/stock/order/adjustmentStock.js
- src/components/pages/stock/order/index.js
- src/components/pages/stock/order/returnStock.js
- src/components/pages/stock/order/transferInventory.js
- src/utils/api/reports-api-utils.js
- src/utils/constants/url-configs.js
shopdesk issues fixations [sd-300]
> SD-300: shopdesk issues fixations [sd-300]

- src/components/organism/table/stock/stockNestedProductsTable.js
- src/components/pages/products/editProduct.js
> JIRA-00: shopdesk issues fixations

- src/components/organism/table/productsNestedTable/productsDiscounts/index.js
- src/components/organism/table/sell/sellHistoryProductsTable.js
- src/components/organism/table/stock/stockReceiveTable.js
- src/components/organism/table/stock/stockTable.js
- src/components/pages/products/productDiscount/index.js
- src/components/pages/register/sell/index.js
- src/components/pages/register/sell/style.scss
- src/components/pages/stock/Po/index.js
> JIRA-00: shopdesk qa issues fixes

- src/components/organism/table/sell/sellNestedProductsTable.js
- src/components/organism/table/stock/stockReceiveTable.js
- src/components/organism/table/stock/stockTable.js
- src/components/pages/products/editProduct.js
- src/components/pages/products/productDiscount/index.js
- src/components/pages/register/salesHistory/index.js
- src/components/pages/register/sell/index.js
- src/components/pages/stock/Po/index.js
- src/components/pages/stock/Po/printPo.scss
- src/components/pages/stock/Po/viewPo.js
> JIRA-00: shopdesk qa issues fixations

- src/components/organism/table/productsNestedTable/productsAdd/productsVariantsNestedTable.js
commit for codebase improvements
> JIRA-00: commit for codebase improvements

- src/components/pages/customers/customerProfile/index.js
- src/components/pages/ecommerce/style.scss
- src/components/pages/products/productAdd/index.js
- src/components/pages/register/salesHistory/index.js
- src/components/pages/register/sell/index.js
- src/components/pages/register/sell/style.scss
- src/components/pages/stock/order/adjustmentStock.js
- src/components/pages/stock/order/index.js
- src/components/pages/stock/order/returnStock.js
- src/components/pages/stock/order/transferInventory.js
- src/utils/api/sales-api-utils.js
> SD-282: commit for fix to [sd-282]

- src/components/organism/table/sell/sellHistoryProductsTable.js
- src/components/pages/register/salesHistory/index.js
minor code changes for fix to [sd-282]
> SD-282: code changes for fix to [sd-282]

- src/components/organism/table/sell/sellHistoryProductsTable.js
- src/components/organism/table/stock/stockTable.js
- src/components/pages/products/index.js
- src/components/pages/register/sell/index.js
- src/components/pages/stock/Po/index.js
- src/utils/api/stock-api-utils.js
- src/utils/constants/url-configs.js
> SD-168: commit for fix to [sd-168]

- src/Routes.js
- src/components/molecules/menu/index.js
- src/components/organism/table/sell/sellHistoryProductsTable.js
- src/components/pages/register/salesHistory/index.js
commit for fixations for shopdesk issues
> JIRA-00: fixations for shopdesk issues

- src/components/pages/products/editProduct.js
- src/components/pages/products/productLookup/index.js
- src/components/pages/products/productsStyleMain.scss
- src/components/pages/register/salesHistory/index.js
- src/components/pages/register/sell/index.js
- src/components/pages/reports/productHistory/index.js
- src/components/pages/reports/style.scss
- src/components/pages/stock/order/adjustmentStock.js
- src/components/pages/stock/order/index.js
- src/components/pages/stock/order/returnStock.js
- src/components/pages/stock/order/transferInventory.js
- src/components/pages/stock/style.scss
- src/utils/helpers/scripts.js
commit for fixations of shopdesk issues
> JIRA-00: fixations of shopdesk issues

- src/components/organism/table/productsNestedTable/productsViewNestedTable.js
- src/components/organism/table/sell/sellNestedProductsTable.js
- src/components/organism/table/sell/sellNestedQuickViewProductsTable.js
- src/components/organism/table/stock/stockNestedProductsTable.js
- src/components/organism/table/stock/stockReceiveTable.js
- src/components/pages/products/productAdd/index.js
- src/components/pages/products/productUpload/index.js
- src/components/pages/register/sell/index.js
- src/components/pages/stock/order/adjustmentStock.js
- src/components/pages/stock/order/index.js
- src/components/pages/stock/order/returnStock.js
- src/components/pages/stock/order/transferInventory.js
- src/utils/helpers/scripts.js
> JIRA-00: fix to shopdesk issues

- src/components/organism/table/sell/sellHistoryProductsTable.js
- src/components/organism/table/sell/sellNestedQuickViewProductsTable.js
- src/components/organism/table/stock/stockTable.js
- src/components/pages/register/salesHistory/index.js
- src/components/pages/stock/Po/index.js
- src/components/pages/stock/Po/viewPo.js
> SD-296: commit for fix to [sd-296]

- src/components/organism/table/sell/sellHistoryProductsTable.js
- src/components/pages/products/editProduct.js
- src/components/pages/stock/Transfer/index.js
- src/components/pages/stock/index.js
- src/components/pages/stock/order/index.js
- src/components/pages/stock/order/transferInventory.js
- src/components/pages/stock/style.scss
- src/utils/api/sales-api-utils.js
- src/utils/api/stock-api-utils.js
- src/utils/constants/url-configs.js
> SD-232: commit for fix to [sd-232]

- src/Routes.js
- src/components/molecules/menu/index.js
- src/components/organism/table/sell/sellHistoryProductsTable.js
- src/components/organism/table/stock/PurchaseOrderviewGrnTable.js
- src/components/organism/table/stock/stockTable.js
- src/components/pages/products/index.js
- src/components/pages/register/salesHistory/index.js
- src/components/pages/register/sell/index.js
- src/components/pages/register/sell/sellInvoice.js
- src/components/pages/stock/Transfer/index.js
- src/components/pages/stock/Transfer/viewGrn.js
- src/components/pages/stock/index.js
- src/utils/api/sales-api-utils.js
- src/utils/api/stock-api-utils.js
- src/utils/constants/url-configs.js
- src/utils/helpers/scripts.js
merging fixes for mariab tasks
> JIRA-00: merging fixes for mariab tasks

- src/components/organism/table/sell/sellHistoryProductsTable.js
- src/components/pages/register/salesHistory/index.js
commit for minor mariab fixes in register module
> JIRA-00: merging commit for minor mariab fixes

- src/components/organism/table/sell/sellHistoryProductsTable.js
- src/components/pages/customers/index.js
merging commit for mariab fixes
> JIRA-00: commit for mariab fixes
